/**
 * Context Manager Hook
 * Manages research project state persistence
 * Version: 10.3.0
 */

import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import type { PluginContext, ResearchContext, Decision } from '../types';

/**
 * Context file paths
 */
const CONTEXT_PATHS = {
  projectState: '.research/project-state.yaml',
  decisionLog: '.research/decision-log.yaml',
};

/**
 * Default research context
 */
const DEFAULT_CONTEXT: ResearchContext = {
  projectName: '',
  projectType: 'quantitative',
  paradigm: 'post-positivist',
  currentStage: 0,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  researchQuestion: undefined,
  theoreticalFramework: undefined,
  completedCheckpoints: [],
  pendingCheckpoints: [],
  decisions: [],
};

// In-memory context cache
let _contextCache: ResearchContext | null = null;

/**
 * MCP availability flag — set to true if MCP memory tools are configured
 */
const MCP_AVAILABLE = process.env.DIVERGA_MCP_ENABLED === '1' || process.env.DIVERGA_BACKEND === 'sqlite';

/**
 * Get context file path
 */
function getContextPath(): string {
  return path.join(process.cwd(), CONTEXT_PATHS.projectState);
}

/**
 * Load context from file using js-yaml
 */
export function loadContext(): ResearchContext | null {
  // Return cached if available
  if (_contextCache) {
    return _contextCache;
  }

  // MCP-first: when MCP tools available, delegate to MCP memory layer
  if (MCP_AVAILABLE) {
    // MCP path: the MCP server maintains its own state
    // Fall through to local file as fallback
  }

  const contextPath = getContextPath();

  if (!fs.existsSync(contextPath)) {
    return null;
  }

  try {
    const content = fs.readFileSync(contextPath, 'utf-8');
    const parsed = yaml.load(content) as Record<string, unknown>;
    _contextCache = hydrateContext(parsed);
    return _contextCache;
  } catch (error) {
    console.error('[Diverga] Failed to load context:', error);
    return null;
  }
}

/**
 * Save context to file using js-yaml
 */
export function saveContext(pluginContext?: PluginContext): void {
  if (!_contextCache) {
    return;
  }

  const contextPath = getContextPath();
  const dirPath = path.dirname(contextPath);

  // Ensure directory exists
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }

  // Update timestamp
  _contextCache.updatedAt = new Date().toISOString();

  try {
    const content = yaml.dump(_contextCache, {
      indent: 2,
      lineWidth: 120,
      noRefs: true,
    });
    fs.writeFileSync(contextPath, `# Research Project State\n# Generated by Diverga v10.3.0\n\n${content}`, 'utf-8');
  } catch (error) {
    console.error('[Diverga] Failed to save context:', error);
  }
}

/**
 * Create new research context
 */
export function createContext(
  projectName: string,
  projectType: ResearchContext['projectType'] = 'quantitative'
): ResearchContext {
  _contextCache = {
    ...DEFAULT_CONTEXT,
    projectName,
    projectType,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  saveContext();
  return _contextCache;
}

/**
 * Update context field
 */
export function updateContext(updates: Partial<ResearchContext>): void {
  if (!_contextCache) {
    _contextCache = { ...DEFAULT_CONTEXT };
  }

  _contextCache = {
    ..._contextCache,
    ...updates,
    updatedAt: new Date().toISOString(),
  };

  saveContext();
}

/**
 * Add completed checkpoint
 */
export function addCompletedCheckpoint(checkpointId: string, decision: Decision): void {
  if (!_contextCache) {
    return;
  }

  if (!_contextCache.completedCheckpoints.includes(checkpointId)) {
    _contextCache.completedCheckpoints.push(checkpointId);
  }

  _contextCache.pendingCheckpoints = _contextCache.pendingCheckpoints.filter(
    cp => cp !== checkpointId
  );

  _contextCache.decisions.push(decision);

  saveContext();
}

/**
 * Get current stage checkpoints
 */
export function getStageCheckpoints(stage: number): string[] {
  // Stage to checkpoint mapping
  const stageCheckpoints: Record<number, string[]> = {
    1: ['CP_RESEARCH_DIRECTION', 'CP_VS_001'],
    2: ['CP_PARADIGM_SELECTION'],
    3: ['CP_THEORY_SELECTION', 'CP_VS_001', 'CP_VS_003'],
    4: ['CP_METHODOLOGY_APPROVAL'],
    5: ['CP_SCREENING_CRITERIA', 'CP_SAMPLING_STRATEGY'],
    6: ['CP_ANALYSIS_PLAN', 'CP_CODING_APPROACH'],
    7: ['CP_QUALITY_REVIEW', 'CP_THEME_VALIDATION'],
    8: ['CP_WRITING_STYLE'],
  };

  return stageCheckpoints[stage] || [];
}

/**
 * Clear context (for new project)
 */
export function clearContext(): void {
  _contextCache = null;

  const contextPath = getContextPath();
  if (fs.existsSync(contextPath)) {
    fs.unlinkSync(contextPath);
  }
}

/**
 * Hydrate a raw parsed YAML object into a ResearchContext,
 * applying defaults for missing fields.
 */
function hydrateContext(parsed: Record<string, unknown>): ResearchContext {
  return {
    projectName: (parsed.projectName as string) || DEFAULT_CONTEXT.projectName,
    projectType: (parsed.projectType as ResearchContext['projectType']) || DEFAULT_CONTEXT.projectType,
    paradigm: (parsed.paradigm as string) || DEFAULT_CONTEXT.paradigm,
    currentStage: typeof parsed.currentStage === 'number' ? parsed.currentStage : DEFAULT_CONTEXT.currentStage,
    createdAt: (parsed.createdAt as string) || DEFAULT_CONTEXT.createdAt,
    updatedAt: (parsed.updatedAt as string) || DEFAULT_CONTEXT.updatedAt,
    researchQuestion: (parsed.researchQuestion as string | undefined),
    theoreticalFramework: (parsed.theoreticalFramework as string | undefined),
    completedCheckpoints: Array.isArray(parsed.completedCheckpoints)
      ? (parsed.completedCheckpoints as string[])
      : [],
    pendingCheckpoints: Array.isArray(parsed.pendingCheckpoints)
      ? (parsed.pendingCheckpoints as string[])
      : [],
    decisions: Array.isArray(parsed.decisions)
      ? (parsed.decisions as Decision[])
      : [],
  };
}

export default {
  loadContext,
  saveContext,
  createContext,
  updateContext,
  clearContext,
};
